/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author Cristian
 */
public class Interfaz extends javax.swing.JFrame {
    
    Prioridad obj=new Prioridad(this);
    int x = 0;

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    /*public JTextArea getGantt() {
        return gantt;
    }

    public void setGantt(JTextArea gantt) {
        this.gantt = gantt;
    } */       
    
    public JLabel getTiempo_real() {
        return tiempo_real;
    }

    public void setTiempo_real(JLabel tiempo_real) {
        this.tiempo_real = tiempo_real;
    }

    public JLabel getCpu_nuevo() {
        return cpu_nuevo1;
    }

    public void setCpu_nuevo(JLabel cpu_nuevo) {
        this.cpu_nuevo1 = cpu_nuevo;
    }

    public JTextArea getTexto_diagrama() {
        return texto_diagrama;
    }

    public void setTexto_diagrama(JTextArea texto_diagrama) {
        this.texto_diagrama = texto_diagrama;
    }



    /*public JTextArea getMensaje() {
        return mensaje;
    }

    public void setMensaje(JTextArea mensaje) {
        this.mensaje = mensaje;
    }*/

    public JLabel getProcesos_en_ejecucion() {
        return procesos_en_ejecucion;
    }

    public void setProcesos_en_ejecucion(JLabel procesos_en_ejecucion) {
        this.procesos_en_ejecucion = procesos_en_ejecucion;
    }

    /*public JTextArea getTexto_atendidos() {
        return texto_atendidos;
    }

    public void setTexto_atendidos(JTextArea texto_atendidos) {
        this.texto_atendidos = texto_atendidos;
    }*/

    public JTextArea getTexto_bloqueados() {
        return texto_bloqueados;
    }

    public void setTexto_bloqueados(JTextArea texto_bloqueados) {
        this.texto_bloqueados = texto_bloqueados;
    }

    public JTextArea getTexto_listos() {
        return texto_listos;
    }

    public void setTexto_listos(JTextArea texto_listos) {
        this.texto_listos = texto_listos;
    }



    public JLabel getTiempo_cpu() {
        return tiempo_cpu;
    }

    public void setTiempo_cpu(JLabel tiempo_cpu) {
        this.tiempo_cpu = tiempo_cpu;
    }      

    public JLabel getTotal_bloqueados() {
        return total_bloqueados;
    }

    public void setTotal_bloqueados(JLabel total_bloqueados) {
        this.total_bloqueados = total_bloqueados;
    }

    public JLabel getTotal_listos() {
        return total_listos;
    }

    public void setTotal_listos(JLabel total_listos) {
        this.total_listos = total_listos;
    }
    
    public JTable getjTableProcesos() {
        return jTableProcesos;
    }

    public void setjTableProcesos(JTable jTable1) {
        this.jTable1 = jTableProcesos;
    }

    
    /**
     * Creates new form Interfaz
     */
    
    
    public Interfaz() {       
        initComponents();
        jTable1.selectAll();
        jTableProcesos.selectAll();
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto_listos = new javax.swing.JTextArea();
        tiempo_cpu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpu_nuevo1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        texto_diagrama = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        total_bloqueados = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        procesos_en_ejecucion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total_listos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tiempo_real = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        texto_bloqueados = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 1365, 740));
        setMinimumSize(new java.awt.Dimension(1365, 740));
        getContentPane().setLayout(null);

        texto_listos.setBackground(java.awt.Color.green);
        texto_listos.setColumns(20);
        texto_listos.setRows(5);
        jScrollPane1.setViewportView(texto_listos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(560, 730, 390, 140);
        getContentPane().add(tiempo_cpu);
        tiempo_cpu.setBounds(530, 820, 63, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Ráfaga ejecutada: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 820, 107, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Tiempo ráfaga proceso:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 820, 133, 14);
        getContentPane().add(cpu_nuevo1);
        cpu_nuevo1.setBounds(290, 820, 62, 14);

        jScrollPane7.setToolTipText("");

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"11", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"12", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"13", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"14", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"15", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"16", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"17", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"18", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"19", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"20", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"21", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"22", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"23", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"24", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"25", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "P", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "TE", "TR"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(0, 0, 102));
        jTable1.setMaximumSize(new java.awt.Dimension(800, 416));
        jTable1.setMinimumSize(new java.awt.Dimension(800, 416));
        jTable1.setPreferredSize(new java.awt.Dimension(2200, 416));
        jScrollPane7.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("P");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("1");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("2");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("3");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("4");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("5");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("6");
            jTable1.getColumnModel().getColumn(7).setHeaderValue("7");
            jTable1.getColumnModel().getColumn(8).setHeaderValue("8");
            jTable1.getColumnModel().getColumn(9).setHeaderValue("9");
            jTable1.getColumnModel().getColumn(10).setHeaderValue("10");
            jTable1.getColumnModel().getColumn(11).setHeaderValue("11");
            jTable1.getColumnModel().getColumn(12).setHeaderValue("12");
            jTable1.getColumnModel().getColumn(13).setHeaderValue("13");
            jTable1.getColumnModel().getColumn(14).setHeaderValue("14");
            jTable1.getColumnModel().getColumn(15).setHeaderValue("15");
            jTable1.getColumnModel().getColumn(16).setHeaderValue("16");
            jTable1.getColumnModel().getColumn(17).setHeaderValue("17");
            jTable1.getColumnModel().getColumn(18).setHeaderValue("18");
            jTable1.getColumnModel().getColumn(19).setHeaderValue("19");
            jTable1.getColumnModel().getColumn(20).setHeaderValue("20");
            jTable1.getColumnModel().getColumn(21).setHeaderValue("21");
            jTable1.getColumnModel().getColumn(22).setHeaderValue("22");
            jTable1.getColumnModel().getColumn(23).setHeaderValue("23");
            jTable1.getColumnModel().getColumn(24).setHeaderValue("24");
            jTable1.getColumnModel().getColumn(25).setHeaderValue("25");
            jTable1.getColumnModel().getColumn(26).setHeaderValue("26");
            jTable1.getColumnModel().getColumn(27).setHeaderValue("27");
            jTable1.getColumnModel().getColumn(28).setHeaderValue("28");
            jTable1.getColumnModel().getColumn(29).setHeaderValue("29");
            jTable1.getColumnModel().getColumn(30).setHeaderValue("30");
            jTable1.getColumnModel().getColumn(31).setHeaderValue("31");
            jTable1.getColumnModel().getColumn(32).setHeaderValue("32");
            jTable1.getColumnModel().getColumn(33).setHeaderValue("33");
            jTable1.getColumnModel().getColumn(34).setHeaderValue("34");
            jTable1.getColumnModel().getColumn(35).setHeaderValue("35");
            jTable1.getColumnModel().getColumn(36).setHeaderValue("36");
            jTable1.getColumnModel().getColumn(37).setHeaderValue("37");
            jTable1.getColumnModel().getColumn(38).setHeaderValue("38");
            jTable1.getColumnModel().getColumn(39).setHeaderValue("39");
            jTable1.getColumnModel().getColumn(40).setHeaderValue("40");
            jTable1.getColumnModel().getColumn(41).setHeaderValue("41");
            jTable1.getColumnModel().getColumn(42).setHeaderValue("42");
            jTable1.getColumnModel().getColumn(43).setHeaderValue("43");
            jTable1.getColumnModel().getColumn(44).setHeaderValue("44");
            jTable1.getColumnModel().getColumn(45).setHeaderValue("45");
            jTable1.getColumnModel().getColumn(46).setHeaderValue("46");
            jTable1.getColumnModel().getColumn(47).setHeaderValue("47");
            jTable1.getColumnModel().getColumn(48).setHeaderValue("48");
            jTable1.getColumnModel().getColumn(49).setHeaderValue("49");
            jTable1.getColumnModel().getColumn(50).setHeaderValue("50");
            jTable1.getColumnModel().getColumn(51).setHeaderValue("51");
            jTable1.getColumnModel().getColumn(52).setHeaderValue("52");
            jTable1.getColumnModel().getColumn(53).setHeaderValue("53");
            jTable1.getColumnModel().getColumn(54).setHeaderValue("54");
            jTable1.getColumnModel().getColumn(55).setHeaderValue("55");
            jTable1.getColumnModel().getColumn(56).setHeaderValue("56");
            jTable1.getColumnModel().getColumn(57).setHeaderValue("57");
            jTable1.getColumnModel().getColumn(58).setHeaderValue("58");
            jTable1.getColumnModel().getColumn(59).setHeaderValue("59");
            jTable1.getColumnModel().getColumn(60).setHeaderValue("60");
            jTable1.getColumnModel().getColumn(61).setHeaderValue("61");
            jTable1.getColumnModel().getColumn(62).setHeaderValue("62");
            jTable1.getColumnModel().getColumn(63).setHeaderValue("63");
            jTable1.getColumnModel().getColumn(64).setHeaderValue("64");
            jTable1.getColumnModel().getColumn(65).setHeaderValue("65");
            jTable1.getColumnModel().getColumn(66).setHeaderValue("66");
            jTable1.getColumnModel().getColumn(67).setHeaderValue("67");
            jTable1.getColumnModel().getColumn(68).setHeaderValue("68");
            jTable1.getColumnModel().getColumn(69).setHeaderValue("69");
            jTable1.getColumnModel().getColumn(70).setHeaderValue("70");
            jTable1.getColumnModel().getColumn(71).setHeaderValue("71");
            jTable1.getColumnModel().getColumn(72).setHeaderValue("72");
            jTable1.getColumnModel().getColumn(73).setHeaderValue("73");
            jTable1.getColumnModel().getColumn(74).setHeaderValue("74");
            jTable1.getColumnModel().getColumn(75).setHeaderValue("75");
            jTable1.getColumnModel().getColumn(76).setHeaderValue("76");
            jTable1.getColumnModel().getColumn(77).setHeaderValue("77");
            jTable1.getColumnModel().getColumn(78).setHeaderValue("78");
            jTable1.getColumnModel().getColumn(79).setHeaderValue("79");
            jTable1.getColumnModel().getColumn(80).setHeaderValue("80");
            jTable1.getColumnModel().getColumn(81).setHeaderValue("81");
            jTable1.getColumnModel().getColumn(82).setHeaderValue("82");
            jTable1.getColumnModel().getColumn(83).setHeaderValue("83");
            jTable1.getColumnModel().getColumn(84).setHeaderValue("84");
            jTable1.getColumnModel().getColumn(85).setHeaderValue("85");
            jTable1.getColumnModel().getColumn(86).setHeaderValue("86");
            jTable1.getColumnModel().getColumn(87).setHeaderValue("87");
            jTable1.getColumnModel().getColumn(88).setHeaderValue("88");
            jTable1.getColumnModel().getColumn(89).setHeaderValue("89");
            jTable1.getColumnModel().getColumn(90).setHeaderValue("90");
            jTable1.getColumnModel().getColumn(91).setHeaderValue("91");
            jTable1.getColumnModel().getColumn(92).setHeaderValue("92");
            jTable1.getColumnModel().getColumn(93).setHeaderValue("93");
            jTable1.getColumnModel().getColumn(94).setHeaderValue("94");
            jTable1.getColumnModel().getColumn(95).setHeaderValue("95");
            jTable1.getColumnModel().getColumn(96).setHeaderValue("96");
            jTable1.getColumnModel().getColumn(97).setHeaderValue("97");
            jTable1.getColumnModel().getColumn(98).setHeaderValue("TE");
            jTable1.getColumnModel().getColumn(99).setHeaderValue("TR");
        }

        getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(6, 393, 990, 310);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel11.setText("DIAGRAMA DE GANNT");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 350, 280, 40);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(469, 416));

        jTableProcesos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProcesos.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#Proceso", "Tiempo Ráfaga", "Tiempo Ejecutado", "Tiempo Espera", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProcesos.setEnabled(false);
        jTableProcesos.setGridColor(new java.awt.Color(0, 0, 102));
        jTableProcesos.setMaximumSize(new java.awt.Dimension(2147483647, 130));
        jTableProcesos.setMinimumSize(new java.awt.Dimension(750, 130));
        jScrollPane3.setViewportView(jTableProcesos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 90, 990, 260);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1370, 10);

        jPanel3.setBackground(new java.awt.Color(255, 248, 210));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 416));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 416));
        jPanel3.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(null);
        jPanel3.add(jPanel11);
        jPanel11.setBounds(0, 60, 1370, 10);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 50)); // NOI18N
        jLabel14.setText("ALGORITMO DE PRIORIDADES - EXPULSIVO");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(140, 0, 1190, 60);

        jPanel10.setBackground(new java.awt.Color(255, 241, 177));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(null);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 0));

        texto_diagrama.setEditable(false);
        texto_diagrama.setColumns(20);
        texto_diagrama.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        texto_diagrama.setRows(5);
        texto_diagrama.setToolTipText("");
        jScrollPane6.setViewportView(texto_diagrama);

        jPanel10.add(jScrollPane6);
        jScrollPane6.setBounds(40, 30, 260, 70);

        jLabel17.setBackground(new java.awt.Color(255, 255, 0));
        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS FINALIZADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel10.add(jLabel17);
        jLabel17.setBounds(20, 10, 300, 110);

        jLabel22.setBackground(new java.awt.Color(255, 255, 0));
        jLabel22.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS FINALIZADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel10.add(jLabel22);
        jLabel22.setBounds(20, 10, 300, 110);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(1010, 550, 330, 140);

        jPanel6.setBackground(new java.awt.Color(255, 241, 177));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton1.setText("INICIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(110, 30, 200, 29);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton2.setText("PAUSAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(110, 60, 200, 29);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton4.setText("REANUDAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(110, 90, 200, 29);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);
        jButton5.setBounds(110, 120, 200, 29);

        jLabel6.setBackground(new java.awt.Color(0, 0, 204));
        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel6.add(jLabel6);
        jLabel6.setBounds(20, 10, 300, 150);

        jPanel1.setBackground(new java.awt.Color(146, 225, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);
        jPanel6.add(jPanel1);
        jPanel1.setBounds(110, 30, 200, 120);

        jLabel16.setBackground(new java.awt.Color(0, 0, 204));
        jLabel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel6.add(jLabel16);
        jLabel16.setBounds(20, 10, 300, 150);

        jPanel7.setBackground(new java.awt.Color(255, 241, 177));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton3.setText("INICIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);
        jButton3.setBounds(110, 30, 200, 29);

        jButton6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton6.setText("PAUSAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);
        jButton6.setBounds(110, 60, 200, 29);

        jButton7.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton7.setText("REANUDAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);
        jButton7.setBounds(110, 90, 200, 29);

        jButton8.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton8.setText("SALIR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8);
        jButton8.setBounds(110, 120, 200, 29);

        jLabel8.setBackground(new java.awt.Color(0, 0, 204));
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel7.add(jLabel8);
        jLabel8.setBounds(20, 10, 300, 150);

        jPanel4.setBackground(new java.awt.Color(146, 225, 238));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);
        jPanel7.add(jPanel4);
        jPanel4.setBounds(110, 30, 200, 120);

        jLabel19.setBackground(new java.awt.Color(0, 0, 204));
        jLabel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel7.add(jLabel19);
        jLabel19.setBounds(20, 10, 300, 150);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(1030, 90, 330, 170);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(1010, 80, 330, 170);

        jPanel8.setBackground(new java.awt.Color(255, 241, 177));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel12.setText("Procesos Bloqueados:");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(110, 70, 150, 15);

        total_bloqueados.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        total_bloqueados.setText("0");
        jPanel8.add(total_bloqueados);
        total_bloqueados.setBounds(250, 70, 65, 15);

        jLabel18.setBackground(new java.awt.Color(204, 0, 51));
        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJECUCIÓN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.add(jLabel18);
        jLabel18.setBounds(20, 10, 300, 110);

        procesos_en_ejecucion.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        procesos_en_ejecucion.setText("0");
        jPanel8.add(procesos_en_ejecucion);
        procesos_en_ejecucion.setBounds(250, 90, 41, 15);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel9.setText("Número de procesos:");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(110, 50, 131, 15);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel3.setText("Tiempo Transcurrido:");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(110, 30, 133, 15);

        total_listos.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        total_listos.setText("0");
        jPanel8.add(total_listos);
        total_listos.setBounds(250, 50, 31, 15);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel4.setText("Proceso en ejecucion: ");
        jPanel8.add(jLabel4);
        jLabel4.setBounds(110, 90, 140, 15);

        tiempo_real.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        tiempo_real.setText("0");
        jPanel8.add(tiempo_real);
        tiempo_real.setBounds(250, 30, 24, 15);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);
        jPanel8.add(jPanel2);
        jPanel2.setBounds(100, 30, 210, 80);

        jLabel20.setBackground(new java.awt.Color(204, 0, 51));
        jLabel20.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EJECUCIÓN", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel8.add(jLabel20);
        jLabel20.setBounds(20, 10, 300, 110);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(1010, 260, 330, 130);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(null);
        jPanel3.add(jPanel13);
        jPanel13.setBounds(0, 700, 1370, 10);

        jPanel9.setBackground(new java.awt.Color(255, 241, 177));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(0, 204, 255));
        jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS BLOQUEADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel9.add(jLabel15);
        jLabel15.setBounds(20, 10, 300, 110);

        jScrollPane8.setBackground(new java.awt.Color(0, 204, 255));

        texto_bloqueados.setEditable(false);
        texto_bloqueados.setColumns(20);
        texto_bloqueados.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        texto_bloqueados.setRows(5);
        texto_bloqueados.setToolTipText("");
        jScrollPane8.setViewportView(texto_bloqueados);

        jPanel9.add(jScrollPane8);
        jScrollPane8.setBounds(40, 30, 260, 70);

        jLabel21.setBackground(new java.awt.Color(0, 204, 255));
        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PROCESOS BLOQUEADOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel9.add(jLabel21);
        jLabel21.setBounds(20, 10, 300, 110);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(1010, 400, 330, 140);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 10, 1370, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(x==0){
            obj.start();
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null, "Ya se inicio la CPU");
        }
        x = x+1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        obj.suspend();
        jButton2.setEnabled(false);
        jButton4.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        obj.resume();
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpu_nuevo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JLabel procesos_en_ejecucion;
    private javax.swing.JTextArea texto_bloqueados;
    private javax.swing.JTextArea texto_diagrama;
    private javax.swing.JTextArea texto_listos;
    private javax.swing.JLabel tiempo_cpu;
    private javax.swing.JLabel tiempo_real;
    private javax.swing.JLabel total_bloqueados;
    private javax.swing.JLabel total_listos;
    // End of variables declaration//GEN-END:variables
}
